apiVersion: v1
kind: Service
metadata:
  name: dotnet-svc
  labels:
    app: dotnet-svc
spec:
  selector:
    app: dotnetapp
  ports:
  - port: 8080 # port on the host
    targetPort: 8080 # port inside the container 
  type: NodePort